services:
  frontend:
    build:
      context: .
    image: juiceapp_frontend
    working_dir: /frontend/
    # restart: always
    volumes:
      - type: bind
        source: ./package.json
        target: /frontend/package.json
      - type: bind
        source: ./package-lock.json
        target: /frontend/package-lock.json
      - type: bind
        source: ./src
        target: /frontend/src
      - type: bind
        source: ./vite.config.js
        target: /frontend/vite.config.js
      - type: bind
        source: ./public
        target: /frontend/public
      - type: bind
        source: ./tsconfig.json
        target: /frontend/tsconfig.json
    tty: true
    ports:
      - 80:3000
    # command: >
    #   npm install
    #   npm start

  # backend:
  #   build:
  #     context: ./backend/
  #   working_dir: /backend/
  #   image: juiceapp_backend
  #   volumes:
  #     - type: bind
  #       source: ./backend/dbdata/
  #       target: /backend/dbdata/