name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Down
      run: docker compose down
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Update submodules
      id: update
      run: git submodule update --remote --recursive
    - name: Build
      run: docker compose up --build -d
    - name: Wait
      run: sleep 2m
    - name: DB init
      run: ./init/init-database.sh
